# CS512 - Machine Learning - 2019
## Homework 1
100 pts


## Goal

The goal of this homework is three-fold:

*   Introduction to the machine learning experimental set up 
*   Gain experience with Decision trees and k-NN approaches
*   Gain experience with the Scikit library

## Dataset
**MNIST** is a collection of 28x28 grayscale images of digits (0-9); hence each pixel is a gray-level from 0-255. 

**Download the data from Keras. You must use a 20% of the training data for validation** (no need for cross-validation as you have plenty of data) and **use the official test data (10,000 samples) only for testing.**

## Task 
Build 2 classifiers (decision tree, k-NN) with the scikit library function calls to classify digits in the MNIST dataset.

## Software: You may find the necessary function references here:
http://scikit-learn.org/stable/supervised_learning.html

## Submission: 
Fill this notebook and submit this document with a link to #your Colab notebook 
(make sure to include the link obtained from the #share link on top right)


##1) Initialize

*   First make a copy of the notebook given to you as a starter.

*   Make sure you choose Connect form upper right.


## 2) Load training dataset

*  Read from Keras library.



In [0]:
#ML HW1
#Samuel Lee
#ID: 24774
#Oct 8, 2019

# Load the Pandas libraries with alias 'pd' 
import pandas as pd 
from keras.datasets import mnist
import numpy as np 

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Read data

# Reshape training to 1D
train_sz = x_train.shape
trainData = np.reshape(x_train, (train_sz[0], train_sz[1]*train_sz[2])).astype('float32')

# Reshape testing to 1D
test_sz = x_test.shape
testData = np.reshape(x_test, (test_sz[0], test_sz[1]*test_sz[2])).astype('float32')

# Normalize
from sklearn.preprocessing import normalize
trainData = normalize(trainData)
testData = normalize(testData)




Using TensorFlow backend.


11493376/11490434 [==============================] - 1s 0us/step


##3) Understanding the dataset

There are alot of functions that can be used to know more about this dataset

- What is the shape of the training set (num of samples X number of attributes) ***[shape function can be used]***

- Display attribute names ***[columns function can be used]***

- Display the first 5 rows from training dataset ***[head or sample functions can be used]***

..

In [0]:
# print shape
print('Training Data:', trainData.shape)
print('Testing Data:', testData.shape)


# print first 5 rows in your dataset

dataset = pd.read_csv("/content/sample_data/mnist_train_small.csv")
dataset.head()

#print(trainData[:5])
#print(testData[:5])
#print(y_train[:])
#print(y_test[:])


Training Data: (60000, 784)
Testing Data: (10000, 784)


6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0  5  0    0    0    0    0  ...      0      0      0      0      0      0
1  7  0    0    0    0    0  ...      0      0      0      0      0      0
2  9  0    0    0    0    0  ...      0      0      0      0      0      0
3  5  0    0    0    0    0  ...      0      0      0      0      0      0
4  2  0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 785 columns]

##4) Shuffle and Split TRAINING data as train (also called development) (80%) and validation (20%) 

In [0]:
from sklearn.utils import shuffle
import random
from sklearn.model_selection import train_test_split

# Shuffle the training data

trainData, y_train = shuffle(trainData, y_train)

# Split 80-20

(train_x, val_x, train_y, val_y) = train_test_split(trainData, y_train , test_size=0.2)



##5) Train decision tree and k-NN  classifiers on development data and do model selection using the validation data

* Train a decision tree classifier with different values of "min_samples_split" which is the minimum number of samples required to split an internal node:  min_samples_split = [default = 2, 3, 5]. 

* Train a k-NN classifier (k=1 and k=5 and rest of the parameters set to default). 

In [0]:

# Train decision tree classifiers


# Train k-NN classifiers

from sklearn.neighbors import KNeighborsClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

min_samples_splits = [2,3,5]

train_results = []
val_results = []


for min_samples_split in min_samples_splits:
  # Fit the tree
  dt = DecisionTreeClassifier(min_samples_split=min_samples_split, criterion='entropy')
  dt.fit(train_x, train_y)
  score = dt.score(val_x, val_y)
  print("For minimum samples split = %d, validation accuracy = %.5f%%" % (min_samples_split, score * 100))
# initialize the values of k to be a list of numbers between 1 and 5
kVals = [1,5]

# Save the accuracies of each value of kVal in [accuracies] variable
# hint: you can use accuracies.append(...) function inside the loop
accuracies = []

# loop over values of k for the k-Nearest Neighbor classifier

for k in kVals:
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(train_x, train_y)
  score = model.score(val_x, val_y)
  print("For k = %d, validation accuracy = %.5f%%" % (k, score * 100))
  accuracies.append(score)
  



For minimum samples split = 2, validation accuracy = 87.80000%
For minimum samples split = 3, validation accuracy = 87.37500%
For minimum samples split = 5, validation accuracy = 87.68333%
For k = 1, validation accuracy = 97.47500%
For k = 5, validation accuracy = 97.50000%


## 7) Test your CHOSEN classifier on Test set

- Load test data
- Apply same pre-processing as training data (probably none)
- Predict the labels of testing data **using the best chosen SINGLE model out of the models (2 approaches, 5 param. setting) that you have tried from step 6 (you have selected your model according to your validation results)** and report the accuracy. 

In [0]:
# Load test data

i = np.argmax(accuracies)
print("best k = %d with %.5f%% validation accuracy" % (kVals[i], accuracies[i] * 100))

# Train KNN with the best k value using [full] training data 
model = KNeighborsClassifier(n_neighbors=kVals[i])
model.fit(trainData, y_train)

# Predict
predictions = model.predict(testData)
from sklearn.metrics import accuracy_score
TestAccuracy = accuracy_score(y_test, predictions)
print("Testing Accuracy = %.5f%%" % (TestAccuracy * 100))

#confusion matrix
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

results = confusion_matrix(y_test, predictions)
print(results)

# Report your result
#
#
#For this homework, the main problem that we are trying to solve is to classify the handwritten image digits into the different classification. FOr example, if the shown image digit is a 4, we are 
#trying to classify this image under the label : "4." For this machine learning model, there are 2 files where one is training with 10000 images, and testing, which has 60000 images. Initially for 
#the training, we use the training file downloaded from MNIST, convert it into a 1dimensional array and shuffle the data. The training data file was split into 80, 20, where 20 percent of the data 
#was used for training the model, and the remaining 80% to test and check the prediction on the accuracy of the model. In order to create a more accurate model, the data in the files were normalized. 
#Minimum Sample Splits         Accuracy
#For val= 2                    87.58333%
#For val= 3                    87.56667%
#For val=5                     87.33333%
#
#For KNN
# K-Value                      Accuracy
# k= 1                         97.59167%
# k= 5                         97.49167%
#
#As a result, we have obtained the best results with the knn classifier with k=1 parameters, giving a digit classification accuracy of 97.59% on the test data. In general, it could be seen from the 
#results that knn had a greater accuracy rate than the decision tree classifier. Furthermore, when the model was applied to the test data, the accuracy was slightly lower, but not by a significant 
#margin. This can actually be a good sign of the model because the sample data which the testing and validation was done on created a suitable model that can be applied to other and bigger data.
#However, during the running process on the google colab processors, I noticed that the running time for the knn classifiers generally took a longer time than the decision tree model, meaning that 
#it required more computational power and was more computationally heavy. In conclusion, when you look at the results of the process on the training data, and the model applied to the actual test data
#it can be implied that the model was suitable and was fitted(without overfitting) in apt amount. 

best k = 5 with 97.50000% validation accuracy
Testing Accuracy = 97.30000%
[[ 975    1    0    0    0    0    3    1    0    0]
 [   0 1131    2    0    0    0    2    0    0    0]
 [  10    2 1006    1    1    0    0    8    4    0]
 [   3    1    3  975    1    9    0    6    9    3]
 [   3    2    0    0  943    0    6    1    2   25]
 [   6    0    0    7    1  860    7    2    6    3]
 [   4    2    0    0    2    2  948    0    0    0]
 [   2   12    6    0    0    0    0  992    0   16]
 [   6    3    3    9    3    5    4    3  934    4]
 [   9    8    2    6    4    3    1    6    4  966]]


##8) Notebook & Report 

**Notebook: As training and testing takes a long time, I will just look at your notebook results; so make sure each cell is run and  outputs are there.**

**Report:** Write an **at most one page summary** of your approach to this problem at the end of your notebook; this should be like an abstract of a paper or the executive summary (you aim for clarity and passing on information, not going to details about known facts such as what dec. trees are or what MNIST is, assuming they are known to people in your research area). 

**Must include statements such as:**

 ( Include the problem definition: 1-2 lines )
 
  (Talk about train/val/test sets, size and how split. )
 
  (Talk about any preprocessing you do.)
  
 ( Give the validation accuracies for different approaches, parameters **in a table** and state which one you selected)
 
 ( State  what your test results are with the chosen method, parameters: e.g. "We have obtained the best results with the ….. classifier      (parameters=....) , giving a digit classification accuracy of …% on test data….""

  (Comment on the speed of the algorithms and anything else that you deem important/interesting (e.g. confusion matrix)).

*You will get full points from here as long as you have a good (enough) summary of your work, regardless of your best performance or what you have decided to talk about in the last few lines.*


##9) Submission

Please submit your **"share link" INLINE in Sucourse submissions**

You should get your "share link" as **share with anyone in edit mode** (just in case)

Please **also submit a 1-page (at most) report in hardcopy** (what you write to step 8) with your name and Hw number etc. to facilitate grading. So step 8 is so that your notebook is complete. The hardcopy is so that grading is easy.


## Questions? 

You should ask all your Google Colab related questions to Discussions and feel free to answer/share your answer regarding Colab. 

You can also ask/answer about which functions to use and what libraries... 

However you should **not ask** about the core parts, that is what is validation/test, which one shd. have higher performance, what are your scores etc.
